# Указываем образ, но может статься, что он единственный (какой ни указывай - будет один)
image: ubuntu:18.04

stages:
  - compile
  - test
  - pages

# Задаём команды, которые будут выполнены до прогона скриптов
before_script:
  - sudo apt-get -y update

# Собираем проект
compile:
  stage: compile
  script:
  # Устанавливаем пакеты
  - sudo apt-get -y install gcc g++
  # Собираем
  - g++ hw.cpp -o hw
  # Сохраняем в артефактах
  artifacts:
    paths:
    - ./hw
    expire_in: 30 minutes

# Автотесты
test:
  stage: test
  script:
  - test/test01
  - test/test02

# Используем GitLab Pages для публикации Doxygen-документации
pages:
  stage: pages
  script:
  # Устанавливаем пакеты
  - sudo apt-get -y install doxygen
  - sudo apt-get -y install graphviz
  # Прогоняем Doxygen
  - doxygen Doxyfile.cfg
  # Диплоим
  - mv doc/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
